name: weekly-scan

on:
  schedule:
    # 7 AM UTC every monday
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run the security scanner
        run: cargo audit
